apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway-service.fullname" . }}
  namespace: {{ .Values.global.namespace | default "ecommerce" }}
  labels:
    {{- include "gateway-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gateway-service.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway-service.labels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.containerPort }}"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: {{ include "gateway-service.fullname" . }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.global.imageTag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef: { name: {{ include "gateway-service.fullname" . }}-config }
            - secretRef: { name: {{ include "gateway-service.fullname" . }}-secret }
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            httpGet: { path: /actuator/health, port: {{ .Values.containerPort }} }
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: {{ .Values.containerPort }} }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: {{ .Values.containerPort }} }
            periodSeconds: 15
            failureThreshold: 3
