apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway-service.fullname" . }}-secret
  namespace: {{ .Values.global.namespace | default "ecommerce" }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.jwtSecret | default "change-me-in-every-environment-this-is-dev-only-do-not-use-in-production-0123456789" | quote }}
