apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: observability
data:
  pipeline.conf: |
    input {
      beats { port => 5044 }
    }

    filter {
      json { source => "message" }
      date { match => ["timestamp", "ISO8601"] target => "@timestamp" }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch.observability.svc.cluster.local:9200"]
        index => "ecommerce-%{[kubernetes][labels][app]}-%{+YYYY.MM.dd}"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: observability
spec:
  replicas: 1
  selector: { matchLabels: { app: logstash } }
  template:
    metadata: { labels: { app: logstash } }
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.16.1
          args: ["-f", "/usr/share/logstash/pipeline/pipeline.conf"]
          ports:
            - { containerPort: 5044, name: beats }
          volumeMounts:
            - { name: config, mountPath: /usr/share/logstash/pipeline }
          resources:
            requests: { cpu: "250m", memory: "1Gi" }
            limits: { cpu: "1", memory: "1536Mi" }
      volumes:
        - name: config
          configMap: { name: logstash-config }
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: observability
spec:
  selector: { app: logstash }
  ports:
    - { port: 5044, targetPort: 5044 }
