filebeat.inputs:
  - type: container
    paths:
      - /var/log/containers/*ecommerce*.log
    processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
            - logs_path: { logs_path: "/var/log/containers/" }

output.logstash:
  hosts: ["logstash.observability.svc.cluster.local:5044"]
