apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-service.fullname" . }}
  namespace: {{ .Values.global.namespace | default "ecommerce" }}
spec:
  type: ClusterIP
  selector:
    {{- include "order-service.labels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}
