spring:
  application:
    name: payment-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_db
    username: payments_user
    password: ${DB_PASSWORD:payments_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8085

security:
  jwt:
    secret: ${JWT_SECRET:change-me-in-every-environment-this-is-dev-only-do-not-use-in-production-0123456789}

resilience4j:
  ratelimiter:
    instances:
      payment-service:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: payment-service
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  structured:
    format:
      console: logstash

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres-payments:5432/payments_db
  kafka:
    bootstrap-servers: kafka:9092
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://otel-collector:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics

---
spring:
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:postgresql://postgres-payments.data.svc.cluster.local:5432/payments_db
  kafka:
    bootstrap-servers: kafka-broker-0.kafka.data.svc.cluster.local:9092,kafka-broker-1.kafka.data.svc.cluster.local:9092,kafka-broker-2.kafka.data.svc.cluster.local:9092
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://otel-collector.observability.svc.cluster.local:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://otel-collector.observability.svc.cluster.local:4318/v1/metrics
