spring:
  application:
    name: user-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: users_user
    password: ${DB_PASSWORD:users_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration

server:
  port: 8081

security:
  jwt:
    secret: ${JWT_SECRET:change-me-in-every-environment-this-is-dev-only-do-not-use-in-production-0123456789}
    access-ttl-minutes: 15

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: user-service
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  structured:
    format:
      console: logstash

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres-users:5432/users_db
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://otel-collector:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics

---
spring:
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:postgresql://postgres-users.data.svc.cluster.local:5432/users_db
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://otel-collector.observability.svc.cluster.local:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://otel-collector.observability.svc.cluster.local:4318/v1/metrics
