apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: ecommerce
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts: [api.company.com]
      secretName: api-company-com-tls
  rules:
    - host: api.company.com
      http:
        paths:
          - path: /users
            pathType: Prefix
            backend: { service: { name: gateway-service, port: { number: 80 } } }
          - path: /products
            pathType: Prefix
            backend: { service: { name: gateway-service, port: { number: 80 } } }
          - path: /inventory
            pathType: Prefix
            backend: { service: { name: gateway-service, port: { number: 80 } } }
          - path: /orders
            pathType: Prefix
            backend: { service: { name: gateway-service, port: { number: 80 } } }
          - path: /payments
            pathType: Prefix
            backend: { service: { name: gateway-service, port: { number: 80 } } }
