apiVersion: v1
kind: Secret
metadata:
  name: gateway-service-secret
  namespace: ecommerce
type: Opaque
stringData:
  JWT_SECRET: "change-me-in-every-environment-this-is-dev-only-do-not-use-in-production-0123456789"
